modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="battleloot"
version="1.0.0"
displayName="Battle Loot"
description='''Konfigurierbare Lootboxen mit eigenem Config-GUI - ideal fuer Battle Royale und Minigames.'''

[[dependencies.battleloot]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.battleloot]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
